---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: default
  name: default
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "default",
      "type": "bridge",
      "bridge": "eth0",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.122.0/24",
        "range_start": "192.168.122.30",
        "range_end": "192.168.122.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: patchnetwork
  name: patchnetwork
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "patchnetwork",
      "type": "macvlan",
      "master": "eth2",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.122.0/24",
        "range_start": "192.168.122.30",
        "range_end": "192.168.122.70"
      }
    }
